---
title: "Vizualization"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)

library(p8105.datasets)
data("weather_df")
```

now we have what we need 

```{r}
weather_df

view(weather_df)
```

scatterplot 

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

I always like the dataframe first 

```{r}
gg_temp_scatterplot=
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

gg_temp_scatterplot
```

making it fancier 

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.25) + 
  geom_smooth(se = FALSE)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.25) + 
  geom_smooth(se = FALSE)
```

the aesthetics are up to you 

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_smooth(se = FALSE)
```

show faceting 

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha=0.5) +
  facet_grid(. ~ name)
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha=0.5) +
  facet_grid(cols = vars(name))
```

lets look at something else 

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = 0.5) + 
  geom_smooth(se=FALSE) +
  facet_grid(. ~ name)
```

make a plot of central park tmax v tmin only and convert temps to F 

```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  mutate(
    tmax = tmax * (9/5) + 32, 
    tmix = tmin * (9/5) + 32
  ) |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```




